server:
  port: 8080
  servlet:
    context-path:
spring:
  application:
    name: SpringBootDemo
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    # name: defaultDataSource
    username: root
    password: 123456
    # 数据库连接池配置
    druid:
      # 初始化
      initial-size: 5
      # 最小连接池数量
      minIdle: 5
      # CPU 核数 + 1，也可以大些但不要超过 20，数据库加锁时连接过多性能下降
      maxActive: 10
      # 最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的 sql，要求是一个查询语句
      validationQuery: SELECT 1
      # 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效
      testWhileIdle: true
      # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: false
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: false
      # 可以支持 PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      # 要启用 PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为 true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的 filters，去掉后监控界面 sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 打开 mergeSql 功能，慢 SQL 记录功能
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置 DruidStatFilter，用于采集 web-jdbc 关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        # 排除一些不必要的 url 过滤
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        # 开启
        enabled: true
        url-pattern: "/druid/*"
        # IP 白名单（没有配置或为空，则只能在本地访问）
        allow: 127.0.0.1
        # IP 黑名单（共同存在时，deny 优先于 allow）
        deny: 192.168.1.73
        # 禁用 HTML 页面上的 Reset-All 功能
        reset-enable: false
        # 可视化界面，自定义登录名
        login-username: admin
        # 可视化界面，自定义登录密码
        login-password: 123456
  thymeleaf:
    # 是否开启模板缓存
    cache: true
    # 是否检查模板路径是否存在
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    # 是否允许 MVC 使用 Thymeleaf
    enabled: true
    # 指定模板的编码
    encoding: UTF-8
    # 指定不使用模板的视图名称，多个以逗号隔开
    excluded-view-names: ''
    # 指定模板的模式
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  resources:
    # 是否开启默认的资源处理，默认 true
    add-mappings: true
    chain:
      # 是否开启缓存，默认为 true
      cache: true
logging:
  level:
    root: info
    com.yyt.springBootDemo: warn
  file:
    name: log/system.log